In [3]:
import pandas as pd
import numpy as np

In [54]:
df=pd.DataFrame(np.arange(24).reshape((12,2)))

In [55]:
df

0   1
0    0   1
1    2   3
2    4   5
3    6   7
4    8   9
5   10  11
6   12  13
7   14  15
8   16  17
9   18  19
10  20  21
11  22  23

In [44]:
state=np.random.RandomState(13)

In [76]:
random_indexer=df.index.values
state.shuffle(random_indexer)

In [77]:
df.index.values

array([ 6,  3,  0,  5, 11, 10,  8,  9,  4,  7,  1,  2])

In [70]:
random_indexer

array([10,  1,  7,  8,  9,  3,  0, 11,  4,  5,  6,  2])

In [71]:
train_idx=random_indexer[:8]
val_idx = random_indexer[8:]

In [72]:
train_idx,val_idx

(array([10,  1,  7,  8,  9,  3,  0, 11]), array([4, 5, 6, 2]))

In [73]:
train_dat=df.loc[train_idx]

In [74]:
train_dat

0   1
10  20  21
1    2   3
7   14  15
8   16  17
9   18  19
3    6   7
0    0   1
11  22  23

In [75]:
len(df)

12

In [ ]:
training['train']